export const WIDGET_LIST_REQUEST = 'WIDGET_LIST_REQUEST'

export const WIDGET_ADD_ITEM = 'WIDGET_ADD_ITEM'
export const WIDGET_EDIT_ITEM = 'WIDGET_EDIT_ITEM'
export const WIDGET_REMOVE_ITEM = 'WIDGET_REMOVE_ITEM'
